extend type Mutation {
  """
  ✨ Insert a single `Category` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  category_insert(
    """
    Data object to insert into the table.
    """
    data: Category_Data!
  ): Category_KeyOutput! @fdc_generated(from: "Category", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Course` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  course_insert(
    """
    Data object to insert into the table.
    """
    data: Course_Data!
  ): Course_KeyOutput! @fdc_generated(from: "Course", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `CourseLesson` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  courseLesson_insert(
    """
    Data object to insert into the table.
    """
    data: CourseLesson_Data!
  ): CourseLesson_KeyOutput! @fdc_generated(from: "CourseLesson", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `CourseModule` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  courseModule_insert(
    """
    Data object to insert into the table.
    """
    data: CourseModule_Data!
  ): CourseModule_KeyOutput! @fdc_generated(from: "CourseModule", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Movie` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  movie_insert(
    """
    Data object to insert into the table.
    """
    data: Movie_Data!
  ): Movie_KeyOutput! @fdc_generated(from: "Movie", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `MovieMetadata` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  movieMetadata_insert(
    """
    Data object to insert into the table.
    """
    data: MovieMetadata_Data!
  ): MovieMetadata_KeyOutput! @fdc_generated(from: "MovieMetadata", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Review` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  review_insert(
    """
    Data object to insert into the table.
    """
    data: Review_Data!
  ): Review_KeyOutput! @fdc_generated(from: "Review", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Category` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  category_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Category_Data!]!
  ): [Category_KeyOutput!]! @fdc_generated(from: "Category", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Course` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  course_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Course_Data!]!
  ): [Course_KeyOutput!]! @fdc_generated(from: "Course", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `CourseLesson` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  courseLesson_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [CourseLesson_Data!]!
  ): [CourseLesson_KeyOutput!]! @fdc_generated(from: "CourseLesson", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `CourseModule` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  courseModule_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [CourseModule_Data!]!
  ): [CourseModule_KeyOutput!]! @fdc_generated(from: "CourseModule", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Movie` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  movie_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Movie_Data!]!
  ): [Movie_KeyOutput!]! @fdc_generated(from: "Movie", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `MovieMetadata` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  movieMetadata_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [MovieMetadata_Data!]!
  ): [MovieMetadata_KeyOutput!]! @fdc_generated(from: "MovieMetadata", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Review` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  review_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Review_Data!]!
  ): [Review_KeyOutput!]! @fdc_generated(from: "Review", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Category` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Category`.
  """
  category_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Category_Data!
  ): Category_KeyOutput! @fdc_generated(from: "Category", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Course` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Course`.
  """
  course_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Course_Data!
  ): Course_KeyOutput! @fdc_generated(from: "Course", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `CourseLesson` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CourseLesson`.
  """
  courseLesson_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: CourseLesson_Data!
  ): CourseLesson_KeyOutput! @fdc_generated(from: "CourseLesson", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `CourseModule` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CourseModule`.
  """
  courseModule_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: CourseModule_Data!
  ): CourseModule_KeyOutput! @fdc_generated(from: "CourseModule", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Movie` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Movie`.
  """
  movie_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Movie_Data!
  ): Movie_KeyOutput! @fdc_generated(from: "Movie", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `MovieMetadata` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MovieMetadata`.
  """
  movieMetadata_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: MovieMetadata_Data!
  ): MovieMetadata_KeyOutput! @fdc_generated(from: "MovieMetadata", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Review` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Review`.
  """
  review_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Review_Data!
  ): Review_KeyOutput! @fdc_generated(from: "Review", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Category` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Category`.
  """
  category_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Category_Data!]!
  ): [Category_KeyOutput!]! @fdc_generated(from: "Category", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Course` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Course`.
  """
  course_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Course_Data!]!
  ): [Course_KeyOutput!]! @fdc_generated(from: "Course", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `CourseLesson` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CourseLesson`.
  """
  courseLesson_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [CourseLesson_Data!]!
  ): [CourseLesson_KeyOutput!]! @fdc_generated(from: "CourseLesson", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `CourseModule` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CourseModule`.
  """
  courseModule_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [CourseModule_Data!]!
  ): [CourseModule_KeyOutput!]! @fdc_generated(from: "CourseModule", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Movie` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Movie`.
  """
  movie_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Movie_Data!]!
  ): [Movie_KeyOutput!]! @fdc_generated(from: "Movie", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `MovieMetadata` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MovieMetadata`.
  """
  movieMetadata_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [MovieMetadata_Data!]!
  ): [MovieMetadata_KeyOutput!]! @fdc_generated(from: "MovieMetadata", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Review` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Review`.
  """
  review_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Review_Data!]!
  ): [Review_KeyOutput!]! @fdc_generated(from: "Review", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Category` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Category` or `null` if not found.
  """
  category_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Category_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Category_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Category_Data!
  ): Category_KeyOutput @fdc_generated(from: "Category", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Course` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Course` or `null` if not found.
  """
  course_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Course_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Course_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Course_Data!
  ): Course_KeyOutput @fdc_generated(from: "Course", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `CourseLesson` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `CourseLesson` or `null` if not found.
  """
  courseLesson_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CourseLesson_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CourseLesson_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: CourseLesson_Data!
  ): CourseLesson_KeyOutput @fdc_generated(from: "CourseLesson", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `CourseModule` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `CourseModule` or `null` if not found.
  """
  courseModule_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CourseModule_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CourseModule_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: CourseModule_Data!
  ): CourseModule_KeyOutput @fdc_generated(from: "CourseModule", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Movie` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Movie` or `null` if not found.
  """
  movie_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Movie_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Movie_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Movie_Data!
  ): Movie_KeyOutput @fdc_generated(from: "Movie", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `MovieMetadata` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `MovieMetadata` or `null` if not found.
  """
  movieMetadata_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MovieMetadata_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MovieMetadata_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: MovieMetadata_Data!
  ): MovieMetadata_KeyOutput @fdc_generated(from: "MovieMetadata", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Review` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Review` or `null` if not found.
  """
  review_update(
    """
    The key used to identify the object.
    """
    key: Review_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Review_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Review_Data!
  ): Review_KeyOutput @fdc_generated(from: "Review", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Category` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  category_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Category_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Category_Data!
  ): Int! @fdc_generated(from: "Category", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Course` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  course_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Course_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Course_Data!
  ): Int! @fdc_generated(from: "Course", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `CourseLesson` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  courseLesson_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: CourseLesson_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: CourseLesson_Data!
  ): Int! @fdc_generated(from: "CourseLesson", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `CourseModule` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  courseModule_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: CourseModule_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: CourseModule_Data!
  ): Int! @fdc_generated(from: "CourseModule", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Movie` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  movie_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Movie_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Movie_Data!
  ): Int! @fdc_generated(from: "Movie", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `MovieMetadata` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  movieMetadata_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: MovieMetadata_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: MovieMetadata_Data!
  ): Int! @fdc_generated(from: "MovieMetadata", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Review` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  review_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Review_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Review_Data!
  ): Int! @fdc_generated(from: "Review", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Category` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  category_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Category_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Category_FirstRow
  ): Category_KeyOutput @fdc_generated(from: "Category", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Course` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  course_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Course_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Course_FirstRow
  ): Course_KeyOutput @fdc_generated(from: "Course", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `CourseLesson` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  courseLesson_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CourseLesson_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CourseLesson_FirstRow
  ): CourseLesson_KeyOutput @fdc_generated(from: "CourseLesson", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `CourseModule` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  courseModule_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CourseModule_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CourseModule_FirstRow
  ): CourseModule_KeyOutput @fdc_generated(from: "CourseModule", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Movie` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  movie_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Movie_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Movie_FirstRow
  ): Movie_KeyOutput @fdc_generated(from: "Movie", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `MovieMetadata` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  movieMetadata_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MovieMetadata_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MovieMetadata_FirstRow
  ): MovieMetadata_KeyOutput @fdc_generated(from: "MovieMetadata", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Review` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  review_delete(
    """
    The key used to identify the object.
    """
    key: Review_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Review_FirstRow
  ): Review_KeyOutput @fdc_generated(from: "Review", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Category` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  category_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Category_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Category", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Course` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  course_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Course_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Course", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `CourseLesson` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  courseLesson_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: CourseLesson_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "CourseLesson", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `CourseModule` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  courseModule_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: CourseModule_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "CourseModule", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Movie` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  movie_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Movie_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Movie", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `MovieMetadata` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  movieMetadata_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: MovieMetadata_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "MovieMetadata", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Review` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  review_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Review_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Review", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
}
